import { TRPCError } from "@trpc/server";
import { sql } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "../db";
import { adminProcedure, router } from "../_core/trpc";
import { deleteLocadoraPrivateFile, parseLocadoraPrivateFile, readLocadoraPrivateFile, storeLocadoraPrivateFile } from "../locadora/storage";

const pageInput = z.object({ tenantId: z.number().int().positive(), page: z.number().int().positive().default(1), pageSize: z.number().int().min(1).max(100).default(20), search: z.string().trim().max(120).optional() });
const tenantInput = z.object({ tenantId: z.number().int().positive() });
const money = z.union([z.string(), z.number()]).optional().nullable();
const nullableString = z.string().trim().max(5000).optional().nullable();

function isoDate(value?: string | null) { return value ? value.slice(0, 10) : null; }
async function dbOrThrow() {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco de dados indisponível." });
  return db as any;
}
async function requireTenant(tenantId: number) {
  const db = await dbOrThrow();
  const result = await db.execute(sql`SELECT id, companyName, isBlocked FROM locadora_tenants WHERE id = ${tenantId} LIMIT 1`);
  const row = (result[0] as any[])[0];
  if (!row) throw new TRPCError({ code: "NOT_FOUND", message: "Locadora não encontrada." });
  if (Number(row.isBlocked) === 1) throw new TRPCError({ code: "FORBIDDEN", message: "Esta locadora está bloqueada." });
  return { db, tenant: row };
}
function paging(page: number, pageSize: number) { return { limit: pageSize, offset: (page - 1) * pageSize }; }
function resultRows(result: any) { return (result?.[0] as any[]) || []; }
function scalar(result: any, field = "total") { return Number(resultRows(result)[0]?.[field] || 0); }
function sqlString(value: string) { return `'${value.replace(/'/g, "''")}'`; }

/**
 * Todas as operações deste router exigem a sessão administrativa do H2.
 * Cada consulta sensível inicia pela validação do tenant, evitando IDOR e
 * qualquer mistura entre locadoras.
 */
export const locadoraRouter = router({
  tenants: router({
    list: adminProcedure.query(async () => {
      const db = await dbOrThrow();
      return resultRows(await db.execute(sql`SELECT id, companyName, ownerName, phone, email, plan, planStatus, isBlocked, createdAt FROM locadora_tenants ORDER BY companyName ASC`));
    }),
    create: adminProcedure.input(z.object({ companyName: z.string().trim().min(2).max(255), ownerName: z.string().trim().max(255).optional(), cpfCnpj: z.string().trim().max(20).optional(), phone: z.string().trim().max(20).optional(), email: z.string().trim().email().max(320).optional(), city: z.string().trim().max(100).optional(), state: z.string().trim().max(2).optional() })).mutation(async ({ input }) => {
      const db = await dbOrThrow();
      const res = await db.execute(sql`INSERT INTO locadora_tenants (companyName, ownerName, cpfCnpj, phone, email, city, state, plan, planStatus) VALUES (${input.companyName}, ${input.ownerName || null}, ${input.cpfCnpj || null}, ${input.phone || null}, ${input.email || null}, ${input.city || null}, ${input.state || null}, 'trial', 'trial')`);
      const insertId = Number((res as any)[0]?.insertId || 0);
      return { id: insertId };
    }),
    update: adminProcedure.input(z.object({ tenantId: z.number().int().positive(), companyName: z.string().trim().min(2).max(255), ownerName: z.string().trim().max(255).optional().nullable(), cpfCnpj: z.string().trim().max(20).optional().nullable(), phone: z.string().trim().max(20).optional().nullable(), email: z.string().trim().email().max(320).optional().nullable(), address: nullableString, city: z.string().trim().max(100).optional().nullable(), state: z.string().trim().max(2).optional().nullable(), zipCode: z.string().trim().max(10).optional().nullable(), whatsapp: z.string().trim().max(20).optional().nullable(), pixKey: nullableString, bankAccount: nullableString, notes: nullableString, plan: z.string().trim().max(32).optional(), planStatus: z.string().trim().max(32).optional(), isBlocked: z.boolean().optional(), blockReason: nullableString })).mutation(async ({ input }) => {
      const { db } = await requireTenant(input.tenantId);
      await db.execute(sql`UPDATE locadora_tenants SET companyName=${input.companyName}, ownerName=${input.ownerName ?? null}, cpfCnpj=${input.cpfCnpj ?? null}, phone=${input.phone ?? null}, email=${input.email ?? null}, address=${input.address ?? null}, city=${input.city ?? null}, state=${input.state ?? null}, zipCode=${input.zipCode ?? null}, whatsapp=${input.whatsapp ?? null}, pixKey=${input.pixKey ?? null}, bankAccount=${input.bankAccount ?? null}, notes=${input.notes ?? null}, plan=${input.plan || 'trial'}, planStatus=${input.planStatus || 'trial'}, isBlocked=${input.isBlocked ? 1 : 0}, blockReason=${input.blockReason ?? null} WHERE id=${input.tenantId}`);
      return { success: true };
    }),
  }),
  dashboard: adminProcedure.input(tenantInput).query(async ({ input }) => {
    const { db, tenant } = await requireTenant(input.tenantId);
    const result = await db.execute(sql`
      SELECT
        (SELECT COUNT(*) FROM locadora_clients WHERE tenantId=${input.tenantId}) AS clients,
        (SELECT COUNT(*) FROM locadora_vehicles WHERE tenantId=${input.tenantId} AND status='available') AS vehiclesAvailable,
        (SELECT COUNT(*) FROM locadora_vehicles WHERE tenantId=${input.tenantId} AND status='rented') AS vehiclesRented,
        (SELECT COUNT(*) FROM locadora_contracts WHERE tenantId=${input.tenantId} AND status='active') AS activeContracts,
        (SELECT COUNT(*) FROM locadora_charges WHERE tenantId=${input.tenantId} AND status IN ('pending','overdue')) AS pendingCharges,
        (SELECT COALESCE(SUM(totalAmount),0) FROM locadora_charges WHERE tenantId=${input.tenantId} AND status IN ('pending','overdue')) AS pendingAmount,
        (SELECT COUNT(*) FROM locadora_maintenances WHERE tenantId=${input.tenantId} AND status='scheduled') AS scheduledMaintenances,
        (SELECT COUNT(*) FROM locadora_alerts WHERE tenantId=${input.tenantId} AND isRead=0) AS unreadAlerts`);
    return { tenant, metrics: resultRows(result)[0] || {} };
  }),
  clients: router({
    list: adminProcedure.input(pageInput).query(async ({ input }) => {
      const { db } = await requireTenant(input.tenantId); const { limit, offset } = paging(input.page, input.pageSize); const q = `%${input.search || ''}%`;
      const rows = resultRows(await db.execute(sql`SELECT * FROM locadora_clients WHERE tenantId=${input.tenantId} AND (${input.search ? sql`fullName LIKE ${q} OR phone LIKE ${q} OR cpfCnpj LIKE ${q}` : sql`1=1`}) ORDER BY id DESC LIMIT ${limit} OFFSET ${offset}`));
      const total = scalar(await db.execute(sql`SELECT COUNT(*) AS total FROM locadora_clients WHERE tenantId=${input.tenantId} AND (${input.search ? sql`fullName LIKE ${q} OR phone LIKE ${q} OR cpfCnpj LIKE ${q}` : sql`1=1`})`));
      return { rows, total, page: input.page, pageSize: input.pageSize };
    }),
    create: adminProcedure.input(z.object({ tenantId: z.number().int().positive(), fullName: z.string().trim().min(2).max(255), cpfCnpj: z.string().trim().max(20).optional(), cnh: z.string().trim().max(30).optional(), phone: z.string().trim().max(20).optional(), whatsapp: z.string().trim().max(20).optional(), email: z.string().trim().email().max(320).optional(), city: z.string().trim().max(100).optional(), state: z.string().trim().max(2).optional(), status: z.enum(['active','blocked','defaulter']).default('active'), notes: nullableString })).mutation(async ({ input }) => {
      const { db } = await requireTenant(input.tenantId); const res = await db.execute(sql`INSERT INTO locadora_clients (tenantId,fullName,cpfCnpj,cnh,phone,whatsapp,email,city,state,status,notes) VALUES (${input.tenantId},${input.fullName},${input.cpfCnpj || null},${input.cnh || null},${input.phone || null},${input.whatsapp || null},${input.email || null},${input.city || null},${input.state || null},${input.status},${input.notes || null})`); return { id: Number((res as any)[0]?.insertId || 0) };
    }),
    update: adminProcedure.input(z.object({ tenantId: z.number().int().positive(), id: z.number().int().positive(), fullName: z.string().trim().min(2).max(255), cpfCnpj: z.string().trim().max(20).optional().nullable(), cnh: z.string().trim().max(30).optional().nullable(), phone: z.string().trim().max(20).optional().nullable(), whatsapp: z.string().trim().max(20).optional().nullable(), email: z.string().trim().email().max(320).optional().nullable(), city: z.string().trim().max(100).optional().nullable(), state: z.string().trim().max(2).optional().nullable(), status: z.enum(['active','blocked','defaulter']), notes: nullableString })).mutation(async ({ input }) => {
      const { db } = await requireTenant(input.tenantId); const r = await db.execute(sql`UPDATE locadora_clients SET fullName=${input.fullName},cpfCnpj=${input.cpfCnpj ?? null},cnh=${input.cnh ?? null},phone=${input.phone ?? null},whatsapp=${input.whatsapp ?? null},email=${input.email ?? null},city=${input.city ?? null},state=${input.state ?? null},status=${input.status},notes=${input.notes ?? null} WHERE id=${input.id} AND tenantId=${input.tenantId}`); if (!Number((r as any)[0]?.affectedRows)) throw new TRPCError({ code:'NOT_FOUND', message:'Cliente não encontrado nesta locadora.' }); return { success:true };
    }),
    remove: adminProcedure.input(z.object({ tenantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ input }) => { const { db } = await requireTenant(input.tenantId); const r = await db.execute(sql`DELETE FROM locadora_clients WHERE id=${input.id} AND tenantId=${input.tenantId} AND NOT EXISTS (SELECT 1 FROM locadora_contracts WHERE tenantId=${input.tenantId} AND clientId=${input.id} AND status='active')`); if (!Number((r as any)[0]?.affectedRows)) throw new TRPCError({ code:'CONFLICT', message:'Cliente não encontrado ou possui contrato ativo.' }); return {success:true}; }),
  }),
  vehicles: router({
    list: adminProcedure.input(pageInput).query(async ({ input }) => { const { db } = await requireTenant(input.tenantId); const { limit, offset } = paging(input.page,input.pageSize); const q=`%${input.search || ''}%`; const rows=resultRows(await db.execute(sql`SELECT * FROM locadora_vehicles WHERE tenantId=${input.tenantId} AND (${input.search ? sql`brand LIKE ${q} OR model LIKE ${q} OR plate LIKE ${q}`:sql`1=1`}) ORDER BY id DESC LIMIT ${limit} OFFSET ${offset}`)); const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_vehicles WHERE tenantId=${input.tenantId} AND (${input.search ? sql`brand LIKE ${q} OR model LIKE ${q} OR plate LIKE ${q}`:sql`1=1`})`)); return {rows,total,page:input.page,pageSize:input.pageSize}; }),
    create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),brand:z.string().trim().min(1).max(100),model:z.string().trim().min(1).max(100),plate:z.string().trim().min(5).max(10),year:z.number().int().min(1900).max(2100).optional(),color:z.string().trim().max(50).optional(),mileage:z.number().int().min(0).optional(),dailyPrice:money,weeklyPrice:money,biweeklyPrice:money,monthlyPrice:money,status:z.enum(['available','rented','maintenance','blocked']).default('available'),notes:nullableString})).mutation(async ({input})=>{const {db}=await requireTenant(input.tenantId); const res=await db.execute(sql`INSERT INTO locadora_vehicles (tenantId,brand,model,plate,year,color,mileage,dailyPrice,weeklyPrice,biweeklyPrice,monthlyPrice,status,notes) VALUES (${input.tenantId},${input.brand},${input.model},${input.plate.toUpperCase()},${input.year||null},${input.color||null},${input.mileage||0},${input.dailyPrice||null},${input.weeklyPrice||null},${input.biweeklyPrice||null},${input.monthlyPrice||null},${input.status},${input.notes||null})`); return {id:Number((res as any)[0]?.insertId||0)};}),
    updateStatus: adminProcedure.input(z.object({tenantId:z.number().int().positive(),id:z.number().int().positive(),status:z.enum(['available','rented','maintenance','blocked'])})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId); const r=await db.execute(sql`UPDATE locadora_vehicles SET status=${input.status} WHERE id=${input.id} AND tenantId=${input.tenantId}`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'NOT_FOUND',message:'Veículo não encontrado nesta locadora.'});return {success:true};}),
    remove: adminProcedure.input(z.object({tenantId:z.number().int().positive(),id:z.number().int().positive()})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`DELETE FROM locadora_vehicles WHERE id=${input.id} AND tenantId=${input.tenantId} AND NOT EXISTS (SELECT 1 FROM locadora_contracts WHERE tenantId=${input.tenantId} AND vehicleId=${input.id} AND status='active')`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'CONFLICT',message:'Veículo não encontrado ou possui contrato ativo.'});return {success:true};}),
  }),
  contracts: router({
    list: adminProcedure.input(pageInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);const {limit,offset}=paging(input.page,input.pageSize);const rows=resultRows(await db.execute(sql`SELECT c.*,cl.fullName clientName,v.brand,v.model,v.plate FROM locadora_contracts c JOIN locadora_clients cl ON cl.id=c.clientId AND cl.tenantId=c.tenantId JOIN locadora_vehicles v ON v.id=c.vehicleId AND v.tenantId=c.tenantId WHERE c.tenantId=${input.tenantId} ORDER BY c.endDate ASC LIMIT ${limit} OFFSET ${offset}`));const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_contracts WHERE tenantId=${input.tenantId}`));return {rows,total,page:input.page,pageSize:input.pageSize};}),
    create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),clientId:z.number().int().positive(),vehicleId:z.number().int().positive(),startDate:z.string().min(10),endDate:z.string().min(10),type:z.enum(['daily','weekly','biweekly','monthly']),value:money,deposit:money,notes:nullableString})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const existing=resultRows(await db.execute(sql`SELECT id FROM locadora_contracts WHERE tenantId=${input.tenantId} AND vehicleId=${input.vehicleId} AND status='active' LIMIT 1`));if(existing.length)throw new TRPCError({code:'CONFLICT',message:'Este veículo já possui contrato ativo.'});const res=await db.execute(sql`INSERT INTO locadora_contracts (tenantId,clientId,vehicleId,startDate,endDate,type,value,deposit,status,notes) SELECT ${input.tenantId},${input.clientId},${input.vehicleId},${isoDate(input.startDate)},${isoDate(input.endDate)},${input.type},${input.value||0},${input.deposit||0},'active',${input.notes||null} WHERE EXISTS (SELECT 1 FROM locadora_clients WHERE id=${input.clientId} AND tenantId=${input.tenantId}) AND EXISTS (SELECT 1 FROM locadora_vehicles WHERE id=${input.vehicleId} AND tenantId=${input.tenantId} AND status='available')`);if(!Number((res as any)[0]?.affectedRows))throw new TRPCError({code:'BAD_REQUEST',message:'Cliente ou veículo inválido para esta locadora.'});await db.execute(sql`UPDATE locadora_vehicles SET status='rented' WHERE id=${input.vehicleId} AND tenantId=${input.tenantId}`);return {id:Number((res as any)[0]?.insertId||0)};}),
    finish: adminProcedure.input(z.object({tenantId:z.number().int().positive(),id:z.number().int().positive(),endMileage:z.number().int().min(0).optional()})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const rows=resultRows(await db.execute(sql`SELECT vehicleId FROM locadora_contracts WHERE id=${input.id} AND tenantId=${input.tenantId} AND status='active' LIMIT 1`));if(!rows.length)throw new TRPCError({code:'NOT_FOUND',message:'Contrato ativo não encontrado.'});await db.execute(sql`UPDATE locadora_contracts SET status='finished', endMileage=${input.endMileage||null} WHERE id=${input.id} AND tenantId=${input.tenantId}`);await db.execute(sql`UPDATE locadora_vehicles SET status='available', mileage=COALESCE(${input.endMileage||null},mileage) WHERE id=${rows[0].vehicleId} AND tenantId=${input.tenantId}`);return {success:true};}),
  }),
  charges: router({
    list: adminProcedure.input(pageInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);const {limit,offset}=paging(input.page,input.pageSize);const rows=resultRows(await db.execute(sql`SELECT ch.*,cl.fullName clientName FROM locadora_charges ch JOIN locadora_clients cl ON cl.id=ch.clientId AND cl.tenantId=ch.tenantId WHERE ch.tenantId=${input.tenantId} ORDER BY ch.dueDate ASC LIMIT ${limit} OFFSET ${offset}`));const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_charges WHERE tenantId=${input.tenantId}`));return {rows,total,page:input.page,pageSize:input.pageSize};}),
    create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),clientId:z.number().int().positive(),contractId:z.number().int().positive().optional(),vehicleId:z.number().int().positive().optional(),description:z.string().trim().max(255).optional(),amount:money,dueDate:z.string().min(10),type:z.enum(['daily','weekly','biweekly','monthly','other']).default('monthly'),notes:nullableString})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const amount=String(input.amount||0);const res=await db.execute(sql`INSERT INTO locadora_charges (tenantId,clientId,contractId,vehicleId,description,amount,totalAmount,dueDate,type,status,notes) SELECT ${input.tenantId},${input.clientId},${input.contractId||null},${input.vehicleId||null},${input.description||null},${amount},${amount},${isoDate(input.dueDate)},${input.type},'pending',${input.notes||null} WHERE EXISTS (SELECT 1 FROM locadora_clients WHERE id=${input.clientId} AND tenantId=${input.tenantId})`);if(!Number((res as any)[0]?.affectedRows))throw new TRPCError({code:'BAD_REQUEST',message:'Cliente inválido para esta locadora.'});return {id:Number((res as any)[0]?.insertId||0)};}),
    markPaid: adminProcedure.input(z.object({tenantId:z.number().int().positive(),id:z.number().int().positive(),paidAmount:money,paymentMethod:z.enum(['pix','cash','card','transfer'])})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`UPDATE locadora_charges SET status='paid',paidAt=NOW(),paidAmount=${input.paidAmount||null},paymentMethod=${input.paymentMethod} WHERE id=${input.id} AND tenantId=${input.tenantId} AND status IN ('pending','overdue')`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'NOT_FOUND',message:'Cobrança pendente não encontrada.'});return {success:true};}),
  }),
  maintenances: router({ list: adminProcedure.input(pageInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);const {limit,offset}=paging(input.page,input.pageSize);const rows=resultRows(await db.execute(sql`SELECT m.*,v.brand,v.model,v.plate FROM locadora_maintenances m JOIN locadora_vehicles v ON v.id=m.vehicleId AND v.tenantId=m.tenantId WHERE m.tenantId=${input.tenantId} ORDER BY m.serviceDate DESC LIMIT ${limit} OFFSET ${offset}`));const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_maintenances WHERE tenantId=${input.tenantId}`));return {rows,total,page:input.page,pageSize:input.pageSize};}), create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),vehicleId:z.number().int().positive(),type:z.string().trim().min(2).max(100),serviceDate:z.string().min(10),cost:money,description:nullableString,notes:nullableString})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`INSERT INTO locadora_maintenances (tenantId,vehicleId,type,serviceDate,cost,description,notes,status) SELECT ${input.tenantId},${input.vehicleId},${input.type},${isoDate(input.serviceDate)},${input.cost||null},${input.description||null},${input.notes||null},'scheduled' WHERE EXISTS (SELECT 1 FROM locadora_vehicles WHERE id=${input.vehicleId} AND tenantId=${input.tenantId})`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'BAD_REQUEST',message:'Veículo inválido para esta locadora.'});return {id:Number((r as any)[0]?.insertId||0)};}) }),
  fines: router({ list: adminProcedure.input(pageInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);const {limit,offset}=paging(input.page,input.pageSize);const rows=resultRows(await db.execute(sql`SELECT f.*,v.plate FROM locadora_fines f JOIN locadora_vehicles v ON v.id=f.vehicleId AND v.tenantId=f.tenantId WHERE f.tenantId=${input.tenantId} ORDER BY f.fineDate DESC LIMIT ${limit} OFFSET ${offset}`));const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_fines WHERE tenantId=${input.tenantId}`));return {rows,total,page:input.page,pageSize:input.pageSize};}), create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),vehicleId:z.number().int().positive(),amount:money,fineDate:z.string().min(10),description:nullableString,dueDate:z.string().min(10).optional()})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`INSERT INTO locadora_fines (tenantId,vehicleId,amount,fineDate,dueDate,description,status) SELECT ${input.tenantId},${input.vehicleId},${input.amount||0},${isoDate(input.fineDate)},${isoDate(input.dueDate)},${input.description||null},'pending' WHERE EXISTS (SELECT 1 FROM locadora_vehicles WHERE id=${input.vehicleId} AND tenantId=${input.tenantId})`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'BAD_REQUEST',message:'Veículo inválido para esta locadora.'});return {id:Number((r as any)[0]?.insertId||0)};}) }),
  employees: router({ list: adminProcedure.input(pageInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);const {limit,offset}=paging(input.page,input.pageSize);const rows=resultRows(await db.execute(sql`SELECT * FROM locadora_employees WHERE tenantId=${input.tenantId} ORDER BY name ASC LIMIT ${limit} OFFSET ${offset}`));const total=scalar(await db.execute(sql`SELECT COUNT(*) total FROM locadora_employees WHERE tenantId=${input.tenantId}`));return {rows,total,page:input.page,pageSize:input.pageSize};}), create: adminProcedure.input(z.object({tenantId:z.number().int().positive(),name:z.string().trim().min(2).max(255),cpf:z.string().trim().max(14).optional(),phone:z.string().trim().max(20).optional(),email:z.string().trim().email().max(320).optional(),role:z.string().trim().max(100).optional(),salary:money})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`INSERT INTO locadora_employees (tenantId,name,cpf,phone,email,role,salary) VALUES (${input.tenantId},${input.name},${input.cpf||null},${input.phone||null},${input.email||null},${input.role||null},${input.salary||null})`);return {id:Number((r as any)[0]?.insertId||0)};}) }),
  alerts: router({ list: adminProcedure.input(tenantInput).query(async({input})=>{const {db}=await requireTenant(input.tenantId);return resultRows(await db.execute(sql`SELECT * FROM locadora_alerts WHERE tenantId=${input.tenantId} ORDER BY isRead ASC,createdAt DESC LIMIT 100`));}), markRead: adminProcedure.input(z.object({tenantId:z.number().int().positive(),id:z.number().int().positive()})).mutation(async({input})=>{const {db}=await requireTenant(input.tenantId);const r=await db.execute(sql`UPDATE locadora_alerts SET isRead=1 WHERE id=${input.id} AND tenantId=${input.tenantId}`);if(!Number((r as any)[0]?.affectedRows))throw new TRPCError({code:'NOT_FOUND',message:'Alerta não encontrado nesta locadora.'});return {success:true};}) }),
  files: router({
    uploadPrivate: adminProcedure.input(z.object({ tenantId:z.number().int().positive(), entity:z.enum(['clientPhoto','clientCnh','vehicleDocument','contractPdf','contractSigned','chargeReceipt','fineReceipt']), entityId:z.number().int().positive(), fileBase64:z.string().min(8) })).mutation(async({input})=>{
      const { db } = await requireTenant(input.tenantId);
      const mapping = {
        clientPhoto: { table:'locadora_clients', column:'photoKey', category:'clientes/foto' }, clientCnh: { table:'locadora_clients', column:'cnhPhotoKey', category:'clientes/cnh' }, vehicleDocument: { table:'locadora_vehicles', column:'documentKey', category:'veiculos/documento' }, contractPdf: { table:'locadora_contracts', column:'pdfKey', category:'contratos/pdf' }, contractSigned: { table:'locadora_contracts', column:'signedContractKey', category:'contratos/assinado' }, chargeReceipt: { table:'locadora_charges', column:'receiptKey', category:'cobrancas/comprovante' }, fineReceipt: { table:'locadora_fines', column:'receiptKey', category:'multas/comprovante' },
      } as const;
      const target = mapping[input.entity];
      const existing = resultRows(await db.execute(sql.raw(`SELECT ${target.column} AS storageKey FROM ${target.table} WHERE id = ${input.entityId} AND tenantId = ${input.tenantId} LIMIT 1`)))[0];
      if (!existing) throw new TRPCError({code:'NOT_FOUND',message:'Registro não encontrado nesta locadora.'});
      const stored = await storeLocadoraPrivateFile(input.tenantId, target.category, parseLocadoraPrivateFile(input.fileBase64));
      await db.execute(sql.raw(`UPDATE ${target.table} SET ${target.column} = ${sqlString(stored.storageKey)} WHERE id = ${input.entityId} AND tenantId = ${input.tenantId}`));
      await deleteLocadoraPrivateFile(existing.storageKey);
      return { success:true, mimeType:stored.mimeType };
    }),
    getPrivate: adminProcedure.input(z.object({ tenantId:z.number().int().positive(), entity:z.enum(['clientPhoto','clientCnh','vehicleDocument','contractPdf','contractSigned','chargeReceipt','fineReceipt']), entityId:z.number().int().positive() })).query(async({input})=>{
      const { db } = await requireTenant(input.tenantId);
      const mapping = { clientPhoto:{table:'locadora_clients',column:'photoKey'},clientCnh:{table:'locadora_clients',column:'cnhPhotoKey'},vehicleDocument:{table:'locadora_vehicles',column:'documentKey'},contractPdf:{table:'locadora_contracts',column:'pdfKey'},contractSigned:{table:'locadora_contracts',column:'signedContractKey'},chargeReceipt:{table:'locadora_charges',column:'receiptKey'},fineReceipt:{table:'locadora_fines',column:'receiptKey'} } as const;
      const target=mapping[input.entity]; const row=resultRows(await db.execute(sql.raw(`SELECT ${target.column} AS storageKey FROM ${target.table} WHERE id = ${input.entityId} AND tenantId = ${input.tenantId} LIMIT 1`)))[0];
      if (!row?.storageKey) throw new TRPCError({code:'NOT_FOUND',message:'Arquivo não encontrado.'}); const file=await readLocadoraPrivateFile(row.storageKey); return { mimeType:file.mimeType, dataBase64:file.buffer.toString('base64') };
    }),
    removePrivate: adminProcedure.input(z.object({ tenantId:z.number().int().positive(), entity:z.enum(['clientPhoto','clientCnh','vehicleDocument','contractPdf','contractSigned','chargeReceipt','fineReceipt']), entityId:z.number().int().positive() })).mutation(async({input})=>{
      const { db } = await requireTenant(input.tenantId); const mapping={clientPhoto:{table:'locadora_clients',column:'photoKey'},clientCnh:{table:'locadora_clients',column:'cnhPhotoKey'},vehicleDocument:{table:'locadora_vehicles',column:'documentKey'},contractPdf:{table:'locadora_contracts',column:'pdfKey'},contractSigned:{table:'locadora_contracts',column:'signedContractKey'},chargeReceipt:{table:'locadora_charges',column:'receiptKey'},fineReceipt:{table:'locadora_fines',column:'receiptKey'}} as const; const target=mapping[input.entity]; const row=resultRows(await db.execute(sql.raw(`SELECT ${target.column} AS storageKey FROM ${target.table} WHERE id = ${input.entityId} AND tenantId = ${input.tenantId} LIMIT 1`)))[0]; if(!row)throw new TRPCError({code:'NOT_FOUND',message:'Registro não encontrado nesta locadora.'}); await db.execute(sql.raw(`UPDATE ${target.table} SET ${target.column} = NULL WHERE id = ${input.entityId} AND tenantId = ${input.tenantId}`)); await deleteLocadoraPrivateFile(row.storageKey); return {success:true};
    }),
  }),
});
