CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`description` text,
	`iconUrl` text,
	`valueRandom` varchar(32) NOT NULL DEFAULT 'Consulte',
	`valueFirst` varchar(32) NOT NULL DEFAULT 'Consulte',
	`valueFull` varchar(32) NOT NULL DEFAULT 'Consulte',
	`enableRandom` int NOT NULL DEFAULT 1,
	`enableFirst` int NOT NULL DEFAULT 1,
	`enableFull` int NOT NULL DEFAULT 0,
	`requireProfilePhoto` int NOT NULL DEFAULT 1,
	`requireCarDocument` int NOT NULL DEFAULT 1,
	`requireAlvara` int NOT NULL DEFAULT 0,
	`requireCondutaxi` int NOT NULL DEFAULT 0,
	`requireVehicle2016` int NOT NULL DEFAULT 0,
	`isPdfOnly` int NOT NULL DEFAULT 0,
	`showYearField` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
