CREATE TABLE IF NOT EXISTS `referralCommissionAttributions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `referrerCustomerId` int,
  `referrerPhone` varchar(32) NOT NULL,
  `referrerName` varchar(128),
  `referredCustomerId` int NOT NULL,
  `referredPhone` varchar(32) NOT NULL,
  `referredName` varchar(128),
  `source` varchar(32) NOT NULL DEFAULT 'cadastro',
  `sourceReference` varchar(128),
  `registrationId` int NOT NULL,
  `orderStatusId` int NOT NULL,
  `orderNumber` int,
  `productId` int,
  `optionId` int,
  `serviceName` varchar(256),
  `serviceOption` varchar(256),
  `commissionRule` varchar(32) NOT NULL DEFAULT 'fixed_option',
  `commissionValue` int NOT NULL DEFAULT 0,
  `status` enum('em_analise','elegivel','paga','nao_elegivel','cancelada') NOT NULL DEFAULT 'em_analise',
  `invalidReason` varchar(512),
  `invalidatedAt` timestamp NULL,
  `eligibleAt` timestamp NULL,
  `paidAt` timestamp NULL,
  `paidBy` varchar(128),
  `paymentReference` varchar(256),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `referralCommissionAttributions_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_referral_commission_order_status` UNIQUE(`orderStatusId`),
  KEY `idx_referral_commission_referrer` (`referrerPhone`,`status`),
  KEY `idx_referral_commission_referred` (`referredPhone`),
  KEY `idx_referral_commission_registration` (`registrationId`)
);
