CREATE TABLE IF NOT EXISTS `h2ads_instance_network_profiles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `instanceId` int NOT NULL,
  `providerName` varchar(128),
  `routeLabel` varchar(128),
  `targetCountryCode` varchar(2),
  `targetCity` varchar(128),
  `expectedIsp` varchar(256),
  `expectedAsn` varchar(32),
  `setupStatus` enum('not_configured','metadata_ready','blocked') NOT NULL DEFAULT 'not_configured',
  `healthStatus` enum('not_checked','healthy','degraded','failed','blocked') NOT NULL DEFAULT 'not_checked',
  `observedIp` varchar(64),
  `observedCountryCode` varchar(2),
  `observedCity` varchar(128),
  `observedIsp` varchar(256),
  `observedAsn` varchar(32),
  `latencyMs` int,
  `lastCheckedAt` timestamp NULL,
  `lastCheckMessage` varchar(512),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `h2ads_network_profile_instance_uq` (`instanceId`),
  KEY `h2ads_network_profile_setup_idx` (`setupStatus`),
  KEY `h2ads_network_profile_health_idx` (`healthStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
