import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, Car, ClipboardList, DollarSign, FileWarning, Gauge, Plus, Users, Wrench, Bell, CheckCircle2, ArrowLeft } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import AdminHeader from "@/components/AdminHeader";
import { trpc } from "@/lib/trpc";

type Tab = "dashboard" | "clients" | "vehicles" | "contracts" | "charges" | "maintenance" | "fines" | "employees" | "alerts";
const tabs: Array<{ id: Tab; label: string; icon: typeof Gauge }> = [
  { id: "dashboard", label: "Visão geral", icon: Gauge }, { id: "clients", label: "Clientes", icon: Users }, { id: "vehicles", label: "Veículos", icon: Car }, { id: "contracts", label: "Contratos", icon: ClipboardList }, { id: "charges", label: "Cobranças", icon: DollarSign }, { id: "maintenance", label: "Manutenção", icon: Wrench }, { id: "fines", label: "Multas", icon: FileWarning }, { id: "employees", label: "Equipe", icon: Users }, { id: "alerts", label: "Alertas", icon: Bell },
];
const input = "w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/30 focus:border-sky-400";
const button = "rounded-xl bg-[#b98a2d] px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-[#d4b15a] disabled:opacity-50";
const smallButton = "rounded-lg bg-white/10 px-3 py-1.5 text-xs font-semibold text-white hover:bg-white/15";
const money = (value: unknown) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

function FormCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><h2 className="mb-4 text-base font-black text-white">{title}</h2>{children}</section>; }
function Metric({ label, value, icon: Icon, tone = "sky" }: { label: string; value: React.ReactNode; icon: typeof Gauge; tone?: "sky" | "emerald" | "amber" | "rose" }) { const colors = { sky:"bg-[#d4b15a]/15 text-[#d9b968] border-sky-400/20", emerald:"bg-emerald-400/15 text-emerald-300 border-emerald-400/20", amber:"bg-amber-400/15 text-amber-300 border-amber-400/20", rose:"bg-rose-400/15 text-rose-300 border-rose-400/20" }; return <div className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl border ${colors[tone]}`}><Icon className="h-4 w-4" /></div><p className="text-2xl font-black text-white">{value}</p><p className="mt-1 text-xs text-white/50">{label}</p></div>; }

export default function AdminLocadora() {
  const [, navigate] = useLocation(); const [tab, setTab] = useState<Tab>("dashboard"); const [tenantId, setTenantId] = useState<number | null>(null); const [creatingTenant, setCreatingTenant] = useState(false);
  const tenants = trpc.locadora.tenants.list.useQuery();
  useEffect(() => { if (!tenantId && tenants.data?.[0]) setTenantId(Number(tenants.data[0].id)); }, [tenantId, tenants.data]);
  const activeTenant = useMemo(() => tenants.data?.find((item: any) => Number(item.id) === tenantId), [tenants.data, tenantId]);
  const enabled = !!tenantId;
  const dashboard = trpc.locadora.dashboard.useQuery({ tenantId: tenantId || 1 }, { enabled });
  const clients = trpc.locadora.clients.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "clients" });
  const vehicles = trpc.locadora.vehicles.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && ["vehicles","contracts","maintenance","fines"].includes(tab) });
  const contracts = trpc.locadora.contracts.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "contracts" });
  const charges = trpc.locadora.charges.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "charges" });
  const maintenances = trpc.locadora.maintenances.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "maintenance" });
  const fines = trpc.locadora.fines.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "fines" });
  const employees = trpc.locadora.employees.list.useQuery({ tenantId: tenantId || 1, page: 1, pageSize: 100 }, { enabled: enabled && tab === "employees" });
  const alerts = trpc.locadora.alerts.list.useQuery({ tenantId: tenantId || 1 }, { enabled: enabled && tab === "alerts" });
  const invalidate = async () => { await Promise.all([tenants.refetch(), dashboard.refetch(), clients.refetch(), vehicles.refetch(), contracts.refetch(), charges.refetch(), maintenances.refetch(), fines.refetch(), employees.refetch(), alerts.refetch()]); };
  const createTenant = trpc.locadora.tenants.create.useMutation({ onSuccess: async (data) => { toast.success("Locadora criada."); setTenantId(data.id); setCreatingTenant(false); await invalidate(); }, onError: (e) => toast.error(e.message) });
  const createClient = trpc.locadora.clients.create.useMutation({ onSuccess: () => { toast.success("Cliente cadastrado."); invalidate(); }, onError:(e)=>toast.error(e.message) });
  const deleteClient = trpc.locadora.clients.remove.useMutation({ onSuccess:()=>{toast.success("Cliente removido.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createVehicle = trpc.locadora.vehicles.create.useMutation({ onSuccess:()=>{toast.success("Veículo cadastrado.");invalidate();},onError:(e)=>toast.error(e.message) });
  const setVehicleStatus = trpc.locadora.vehicles.updateStatus.useMutation({ onSuccess:()=>{toast.success("Status atualizado.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createContract = trpc.locadora.contracts.create.useMutation({ onSuccess:()=>{toast.success("Contrato criado e veículo reservado.");invalidate();},onError:(e)=>toast.error(e.message) });
  const finishContract = trpc.locadora.contracts.finish.useMutation({ onSuccess:()=>{toast.success("Contrato finalizado; veículo liberado.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createCharge = trpc.locadora.charges.create.useMutation({ onSuccess:()=>{toast.success("Cobrança criada.");invalidate();},onError:(e)=>toast.error(e.message) });
  const markPaid = trpc.locadora.charges.markPaid.useMutation({ onSuccess:()=>{toast.success("Cobrança marcada como paga.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createMaintenance = trpc.locadora.maintenances.create.useMutation({ onSuccess:()=>{toast.success("Manutenção registrada.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createFine = trpc.locadora.fines.create.useMutation({ onSuccess:()=>{toast.success("Multa registrada.");invalidate();},onError:(e)=>toast.error(e.message) });
  const createEmployee = trpc.locadora.employees.create.useMutation({ onSuccess:()=>{toast.success("Funcionário cadastrado.");invalidate();},onError:(e)=>toast.error(e.message) });
  const markAlert = trpc.locadora.alerts.markRead.useMutation({ onSuccess:()=>{toast.success("Alerta marcado como lido.");invalidate();},onError:(e)=>toast.error(e.message) });

  function submitTenant(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); createTenant.mutate({ companyName:String(f.get("companyName")||""), ownerName:String(f.get("ownerName")||"") || undefined, phone:String(f.get("phone")||"") || undefined, email:String(f.get("email")||"") || undefined, city:String(f.get("city")||"") || undefined, state:String(f.get("state")||"") || undefined }); }
  if (!tenantId || creatingTenant) return <div className="min-h-screen bg-[#090a0d]"><AdminHeader title="Locadora" icon={<img src="/locadora/assets/locacar-icon-192-v1.png" alt="" className="h-6 w-6 rounded-md object-cover"/>} backTo="/admin/codes"/><main className="mx-auto max-w-xl px-4 py-8"><FormCard title="Criar locadora"><p className="mb-5 text-sm text-white/55">Cadastre a empresa antes de incluir clientes, veículos e contratos. Os dados desta empresa ficarão isolados das demais.</p><form onSubmit={submitTenant} className="grid gap-3"><input required name="companyName" className={input} placeholder="Nome da locadora *"/><input name="ownerName" className={input} placeholder="Responsável"/><div className="grid grid-cols-2 gap-3"><input name="phone" className={input} placeholder="Telefone"/><input name="city" className={input} placeholder="Cidade"/></div><div className="grid grid-cols-[1fr_90px] gap-3"><input type="email" name="email" className={input} placeholder="E-mail"/><input name="state" maxLength={2} className={input} placeholder="UF"/></div><button disabled={createTenant.isPending} className={button}>{createTenant.isPending?"Criando...":"Criar locadora"}</button>{tenants.data?.length ? <button type="button" className={smallButton} onClick={()=>setCreatingTenant(false)}>Cancelar</button>:null}</form></FormCard></main></div>;

  const m: any = dashboard.data?.metrics || {};
  return <div className="min-h-screen bg-[#090a0d] text-white"><AdminHeader title="Locadora" icon={<img src="/locadora/assets/locacar-icon-192-v1.png" alt="" className="h-6 w-6 rounded-md object-cover"/>} backTo="/admin/codes"/><main className="mx-auto max-w-7xl px-4 py-5"><div className="mb-5 flex flex-wrap items-center gap-3 rounded-2xl border border-[#b98a2d]/30 bg-[#b98a2d]/10 p-3"><Building2 className="h-5 w-5 text-[#d9b968]"/><select className="min-w-[220px] flex-1 bg-transparent text-sm font-bold outline-none" value={tenantId || ""} onChange={e=>setTenantId(Number(e.target.value))}>{tenants.data?.map((t:any)=><option className="bg-slate-900" key={t.id} value={t.id}>{t.companyName}</option>)}</select><button className={smallButton} onClick={()=>setCreatingTenant(true)}><Plus className="mr-1 inline h-3 w-3"/>Nova locadora</button><button className={smallButton} onClick={()=>navigate("/locadora")}>Ver área da locadora</button></div><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${tab===id?"bg-[#d4b15a] text-slate-950":"bg-white/5 text-white/65 hover:bg-white/10"}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div>
  {tab==="dashboard"&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Clientes cadastrados" value={m.clients||0} icon={Users}/><Metric label="Veículos disponíveis" value={m.vehiclesAvailable||0} icon={Car} tone="emerald"/><Metric label="Contratos ativos" value={m.activeContracts||0} icon={ClipboardList} tone="amber"/><Metric label="A receber" value={money(m.pendingAmount)} icon={DollarSign} tone="rose"/><Metric label="Veículos alugados" value={m.vehiclesRented||0} icon={Car}/><Metric label="Manutenções previstas" value={m.scheduledMaintenances||0} icon={Wrench} tone="amber"/><Metric label="Cobranças pendentes" value={m.pendingCharges||0} icon={DollarSign} tone="rose"/><Metric label="Alertas não lidos" value={m.unreadAlerts||0} icon={Bell} tone="amber"/></div>}
  {tab==="clients"&&<ClientsPanel tenantId={tenantId} rows={(clients.data?.rows||[]) as any[]} onCreate={(v)=>createClient.mutate({...v,tenantId})} onDelete={(id)=>deleteClient.mutate({tenantId,id})}/>} 
  {tab==="vehicles"&&<VehiclesPanel tenantId={tenantId} rows={(vehicles.data?.rows||[]) as any[]} onCreate={(v)=>createVehicle.mutate({...v,tenantId})} onStatus={(id,status)=>setVehicleStatus.mutate({tenantId,id,status})}/>} 
  {tab==="contracts"&&<ContractsPanel tenantId={tenantId} clients={(clients.data?.rows||[]) as any[]} vehicles={(vehicles.data?.rows||[]) as any[]} rows={(contracts.data?.rows||[]) as any[]} onCreate={(v)=>createContract.mutate({...v,tenantId})} onFinish={(id)=>finishContract.mutate({tenantId,id})}/>} 
  {tab==="charges"&&<ChargesPanel tenantId={tenantId} clients={(clients.data?.rows||[]) as any[]} rows={(charges.data?.rows||[]) as any[]} onCreate={(v)=>createCharge.mutate({...v,tenantId})} onPaid={(id)=>markPaid.mutate({tenantId,id,paymentMethod:"pix"})}/>} 
  {tab==="maintenance"&&<MaintenancePanel tenantId={tenantId} vehicles={(vehicles.data?.rows||[]) as any[]} rows={(maintenances.data?.rows||[]) as any[]} onCreate={(v)=>createMaintenance.mutate({...v,tenantId})}/>} 
  {tab==="fines"&&<FinesPanel tenantId={tenantId} vehicles={(vehicles.data?.rows||[]) as any[]} rows={(fines.data?.rows||[]) as any[]} onCreate={(v)=>createFine.mutate({...v,tenantId})}/>} 
  {tab==="employees"&&<EmployeesPanel rows={(employees.data?.rows||[]) as any[]} onCreate={(v)=>createEmployee.mutate({...v,tenantId})}/>} 
  {tab==="alerts"&&<AlertsPanel rows={(alerts.data||[]) as any[]} onRead={(id)=>markAlert.mutate({tenantId,id})}/>} 
  </main></div>;
}

function Table({children}:{children:React.ReactNode}){return <div className="overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table className="w-full min-w-[620px] text-left text-sm">{children}</table></div>}
function ClientsPanel({rows,onCreate,onDelete}:{tenantId:number;rows:any[];onCreate:(v:any)=>void;onDelete:(id:number)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Novo cliente"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({fullName:String(f.get('name')),phone:String(f.get('phone'))||undefined,cpfCnpj:String(f.get('cpf'))||undefined,email:String(f.get('email'))||undefined,city:String(f.get('city'))||undefined,status:'active'});e.currentTarget.reset();}}><input required name="name" className={input} placeholder="Nome completo *"/><input name="cpf" className={input} placeholder="CPF/CNPJ"/><input name="phone" className={input} placeholder="Telefone"/><input name="email" type="email" className={input} placeholder="E-mail"/><input name="city" className={input} placeholder="Cidade"/><button className={button}><Plus className="mr-1 inline h-4 w-4"/>Cadastrar cliente</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Cliente</th><th>Contato</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.fullName}<p className="text-xs text-white/40">{r.cpfCnpj||'—'}</p></td><td>{r.phone||r.email||'—'}</td><td><span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs text-emerald-300">{r.status}</span></td><td><button className={smallButton} onClick={()=>onDelete(Number(r.id))}>Excluir</button></td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={4}>Nenhum cliente cadastrado.</td></tr>}</tbody></Table></div>}
function VehiclesPanel({rows,onCreate,onStatus}:{tenantId:number;rows:any[];onCreate:(v:any)=>void;onStatus:(id:number,status:any)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Novo veículo"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({brand:String(f.get('brand')),model:String(f.get('model')),plate:String(f.get('plate')),year:Number(f.get('year'))||undefined,dailyPrice:String(f.get('daily'))||undefined,weeklyPrice:String(f.get('weekly'))||undefined,biweeklyPrice:String(f.get('biweekly'))||undefined,monthlyPrice:String(f.get('monthly'))||undefined,status:'available'});e.currentTarget.reset();}}><div className="grid grid-cols-2 gap-3"><input required name="brand" className={input} placeholder="Marca *"/><input required name="model" className={input} placeholder="Modelo *"/></div><div className="grid grid-cols-2 gap-3"><input required name="plate" className={input} placeholder="Placa *"/><input type="number" name="year" className={input} placeholder="Ano"/></div><div className="grid grid-cols-2 gap-3"><input name="daily" className={input} placeholder="Valor diário"/><input name="weekly" className={input} placeholder="Valor semanal"/></div><div className="grid grid-cols-2 gap-3"><input name="biweekly" className={input} placeholder="Valor quinzenal"/><input name="monthly" className={input} placeholder="Valor mensal"/></div><button className={button}>Cadastrar veículo</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Veículo</th><th>Placa</th><th>Valores</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.brand} {r.model}<p className="text-xs text-white/40">{r.year||'—'}</p></td><td>{r.plate}</td><td>{r.dailyPrice?`${money(r.dailyPrice)}/dia`:r.weeklyPrice?`${money(r.weeklyPrice)}/sem`:r.biweeklyPrice?`${money(r.biweeklyPrice)}/quinzena`:r.monthlyPrice?`${money(r.monthlyPrice)}/mês`:'—'}</td><td><select className="rounded-lg bg-slate-950 p-2 text-xs" value={r.status} onChange={e=>onStatus(Number(r.id),e.target.value)}><option value="available">Disponível</option><option value="rented">Alugado</option><option value="maintenance">Manutenção</option><option value="blocked">Bloqueado</option></select></td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={4}>Nenhum veículo cadastrado.</td></tr>}</tbody></Table></div>}
function ContractsPanel({clients,vehicles,rows,onCreate,onFinish}:{tenantId:number;clients:any[];vehicles:any[];rows:any[];onCreate:(v:any)=>void;onFinish:(id:number)=>void}){return <div className="grid gap-4 lg:grid-cols-[380px_1fr]"><FormCard title="Novo contrato"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({clientId:Number(f.get('client')),vehicleId:Number(f.get('vehicle')),startDate:String(f.get('start')),endDate:String(f.get('end')),type:String(f.get('type')),value:String(f.get('value')),deposit:String(f.get('deposit'))||undefined});e.currentTarget.reset();}}><select required name="client" className={input}><option value="">Cliente *</option>{clients.map(c=><option key={c.id} value={c.id}>{c.fullName}</option>)}</select><select required name="vehicle" className={input}><option value="">Veículo disponível *</option>{vehicles.filter(v=>v.status==='available').map(v=><option key={v.id} value={v.id}>{v.brand} {v.model} — {v.plate}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required name="start" type="date" className={input}/><input required name="end" type="date" className={input}/></div><select name="type" className={input}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="monthly">Mensal</option></select><div className="grid grid-cols-2 gap-3"><input required name="value" className={input} placeholder="Valor *"/><input name="deposit" className={input} placeholder="Caução"/></div><button className={button}>Criar contrato</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Cliente</th><th>Veículo</th><th>Período</th><th>Valor</th><th></th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.clientName}</td><td>{r.brand} {r.model}<p className="text-xs text-white/40">{r.plate}</p></td><td>{String(r.startDate).slice(0,10)} → {String(r.endDate).slice(0,10)}</td><td>{money(r.value)}</td><td>{r.status==='active'?<button className={smallButton} onClick={()=>onFinish(Number(r.id))}>Finalizar</button>:<span className="text-xs text-white/45">{r.status}</span>}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={5}>Nenhum contrato cadastrado.</td></tr>}</tbody></Table></div>}
function ChargesPanel({clients,rows,onCreate,onPaid}:{tenantId:number;clients:any[];rows:any[];onCreate:(v:any)=>void;onPaid:(id:number)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Nova cobrança"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({clientId:Number(f.get('client')),description:String(f.get('description'))||undefined,amount:String(f.get('amount')),dueDate:String(f.get('due')),type:String(f.get('type'))});e.currentTarget.reset();}}><select required name="client" className={input}><option value="">Cliente *</option>{clients.map(c=><option key={c.id} value={c.id}>{c.fullName}</option>)}</select><input name="description" className={input} placeholder="Descrição"/><input required name="amount" className={input} placeholder="Valor *"/><input required type="date" name="due" className={input}/><select name="type" className={input}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="monthly">Mensal</option><option value="other">Outra</option></select><button className={button}>Criar cobrança</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Cliente</th><th>Vencimento</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.clientName}<p className="text-xs text-white/40">{r.description||'Cobrança'}</p></td><td>{String(r.dueDate).slice(0,10)}</td><td>{money(r.totalAmount)}</td><td>{r.status}</td><td>{r.status!=='paid'&&<button className={smallButton} onClick={()=>onPaid(Number(r.id))}><CheckCircle2 className="mr-1 inline h-3 w-3"/>Pago</button>}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={5}>Nenhuma cobrança cadastrada.</td></tr>}</tbody></Table></div>}
function MaintenancePanel({vehicles,rows,onCreate}:{tenantId:number;vehicles:any[];rows:any[];onCreate:(v:any)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Registrar manutenção"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({vehicleId:Number(f.get('vehicle')),type:String(f.get('type')),serviceDate:String(f.get('date')),cost:String(f.get('cost'))||undefined,description:String(f.get('description'))||undefined});e.currentTarget.reset();}}><select name="vehicle" required className={input}><option value="">Veículo *</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.brand} {v.model} — {v.plate}</option>)}</select><input name="type" required className={input} placeholder="Tipo de serviço *"/><input name="date" type="date" required className={input}/><input name="cost" className={input} placeholder="Custo"/><input name="description" className={input} placeholder="Descrição"/><button className={button}>Registrar manutenção</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Veículo</th><th>Serviço</th><th>Data</th><th>Custo</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.brand} {r.model}<p className="text-xs text-white/40">{r.plate}</p></td><td>{r.type}</td><td>{String(r.serviceDate).slice(0,10)}</td><td>{r.cost?money(r.cost):'—'}</td><td>{r.status}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={5}>Nenhuma manutenção registrada.</td></tr>}</tbody></Table></div>}
function FinesPanel({vehicles,rows,onCreate}:{tenantId:number;vehicles:any[];rows:any[];onCreate:(v:any)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Registrar multa"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({vehicleId:Number(f.get('vehicle')),amount:String(f.get('amount')),fineDate:String(f.get('date')),dueDate:String(f.get('due'))||undefined,description:String(f.get('description'))||undefined});e.currentTarget.reset();}}><select name="vehicle" required className={input}><option value="">Veículo *</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.brand} {v.model} — {v.plate}</option>)}</select><input name="amount" required className={input} placeholder="Valor *"/><input name="date" required type="date" className={input}/><input name="due" type="date" className={input}/><input name="description" className={input} placeholder="Descrição"/><button className={button}>Registrar multa</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Veículo</th><th>Data</th><th>Valor</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.plate}</td><td>{String(r.fineDate).slice(0,10)}</td><td>{money(r.amount)}</td><td>{r.status}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={4}>Nenhuma multa registrada.</td></tr>}</tbody></Table></div>}
function EmployeesPanel({rows,onCreate}:{rows:any[];onCreate:(v:any)=>void}){return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><FormCard title="Novo funcionário"><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onCreate({name:String(f.get('name')),cpf:String(f.get('cpf'))||undefined,phone:String(f.get('phone'))||undefined,email:String(f.get('email'))||undefined,role:String(f.get('role'))||undefined,salary:String(f.get('salary'))||undefined});e.currentTarget.reset();}}><input name="name" required className={input} placeholder="Nome *"/><input name="cpf" className={input} placeholder="CPF"/><input name="phone" className={input} placeholder="Telefone"/><input name="email" type="email" className={input} placeholder="E-mail"/><input name="role" className={input} placeholder="Função"/><input name="salary" className={input} placeholder="Salário"/><button className={button}>Cadastrar funcionário</button></form></FormCard><Table><thead className="border-b border-white/10 text-xs text-white/45"><tr><th className="p-3">Nome</th><th>Função</th><th>Contato</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-b border-white/5" key={r.id}><td className="p-3 font-semibold">{r.name}</td><td>{r.role||'—'}</td><td>{r.phone||r.email||'—'}</td><td>{r.status}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-white/45" colSpan={4}>Nenhum funcionário cadastrado.</td></tr>}</tbody></Table></div>}
function AlertsPanel({rows,onRead}:{rows:any[];onRead:(id:number)=>void}){return <FormCard title="Alertas operacionais"><div className="space-y-2">{rows.map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><Bell className="h-4 w-4 text-amber-300"/><div className="flex-1"><p className="font-bold text-white">{r.title}</p><p className="text-xs text-white/55">{r.message||'Sem detalhes adicionais.'}</p></div>{!Number(r.isRead)&&<button className={smallButton} onClick={()=>onRead(Number(r.id))}>Marcar lido</button>}</div>)}{!rows.length&&<p className="text-sm text-white/45">Nenhum alerta pendente.</p>}</div></FormCard>}
