import { useParams } from "wouter";
import { CheckCircle2, Download, FileText, Loader2, ShieldCheck, XCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";

function money(value: unknown) { return Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }

export default function PublicReceiptPage() {
  const params = useParams();
  const publicToken = String((params as any).publicToken || "");
  const receiptQuery = trpc.privateTransport.receipts.getPublic.useQuery({ publicToken }, { enabled: !!publicToken, retry: false });
  if (receiptQuery.isLoading) return <Frame><div className="flex min-h-80 flex-col items-center justify-center gap-3 text-slate-300"><Loader2 className="h-8 w-8 animate-spin text-cyan-300" /><p className="text-sm font-semibold">Carregando recibo...</p></div></Frame>;
  if (receiptQuery.error || !receiptQuery.data) return <Frame><div className="mx-auto max-w-md py-16 text-center"><XCircle className="mx-auto h-12 w-12 text-red-300" /><h1 className="mt-4 text-2xl font-black text-white">Recibo indisponível</h1><p className="mt-2 text-sm text-slate-400">{receiptQuery.error?.message || "O link é inválido ou foi desativado."}</p></div></Frame>;
  const { receipt } = receiptQuery.data; const snapshot: any = receipt.snapshot || {};
  return <Frame><main className="mx-auto max-w-2xl px-4 py-6 sm:py-10"><section className="overflow-hidden rounded-3xl border border-emerald-400/20 bg-slate-950 shadow-2xl shadow-emerald-950/25"><header className="bg-gradient-to-br from-emerald-500/25 via-teal-950 to-slate-950 px-5 py-6 sm:px-8"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-400/15 text-emerald-200"><CheckCircle2 className="h-6 w-6" /></div><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-200">H2 Particular</p><h1 className="mt-1 text-xl font-black text-white sm:text-2xl">Recibo de pagamento</h1></div></div></header><div className="space-y-6 p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Recibo nº</p><p className="mt-1 text-lg font-black text-white">{receipt.receiptCode}</p></div><span className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-black text-emerald-200">PAGAMENTO CONFIRMADO</span></div><div className="rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-5 text-center"><p className="text-xs font-bold uppercase tracking-widest text-emerald-200">Valor recebido</p><p className="mt-2 text-4xl font-black text-white">{money(receipt.amount)}</p><p className="mt-2 text-sm text-emerald-100/80">{receipt.paymentMethod} • {new Date(receipt.paidAt).toLocaleString("pt-BR")}</p></div><div className="grid gap-4 sm:grid-cols-2"><Info label="Passageiro" value={snapshot.clientName || "—"} /><Info label="Motorista" value={snapshot.driverName || "—"} /><Info label="Data da viagem" value={snapshot.tripDateFormatted || "—"} /><Info label="Veículo" value={snapshot.vehicle || "—"} /></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Referente ao transporte</p><p className="mt-3 text-sm font-semibold text-white">{snapshot.pickupAddress || "—"}</p><p className="my-2 text-xs text-cyan-300">↓ destino</p><p className="text-sm font-semibold text-white">{snapshot.destinationAddress || "—"}</p></div>{receipt.pdfUrl && <Button onClick={() => window.open(receipt.pdfUrl, "_blank", "noopener,noreferrer")} className="h-12 w-full bg-emerald-500 text-base font-black text-slate-950 hover:bg-emerald-400"><Download className="mr-2 h-4 w-4" />Baixar recibo em PDF</Button>}<div className="flex items-center justify-center gap-2 border-t border-white/10 pt-5 text-center text-xs text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-300" />Documento emitido pelo H2 Particular</div></div></section></main></Frame>;
}
function Frame({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[#060914] text-white">{children}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1.5 text-sm font-bold text-white">{value}</p></div>; }
