from pathlib import Path


def once(text, old, new, label):
    c = text.count(old)
    if c != 1:
        raise SystemExit(f'{label}: expected 1 anchor, found {c}')
    return text.replace(old, new, 1)

p = Path('shared/vipInstallments.ts')
t = p.read_text(encoding='utf-8')
t = once(t, '  interestBps: number;\n  firstDueDate: string;', '  interestBps: number;\n  firstInstallmentAmountCents?: number | null;\n  firstDueDate: string;', 'shared input')
t = once(t, '  interestAmountCents: number;\n  totalAmountCents: number;', '  interestAmountCents: number;\n  financedBaseAmountCents: number;\n  firstInstallmentAmountCents: number | null;\n  totalAmountCents: number;', 'shared quote fields')
t = once(t, '''  const interestAmountCents = Math.round((input.baseAmountCents * input.interestBps) / 10_000);\n  const totalAmountCents = input.baseAmountCents + interestAmountCents;\n  if (!Number.isSafeInteger(totalAmountCents) || totalAmountCents > MAX_SAFE_MONEY_CENTS) {\n    throw new Error("Valor total fora do limite permitido.");\n  }\n\n  const amounts = splitInstallmentAmounts(totalAmountCents, input.installmentCount);''', '''  const specialFirst = input.firstInstallmentAmountCents == null ? null : input.firstInstallmentAmountCents;\n  if (specialFirst != null) {\n    assertInteger("Valor da entrada", specialFirst, 1, MAX_SAFE_MONEY_CENTS);\n    if (specialFirst >= input.baseAmountCents) throw new Error("A entrada deve ser menor que o valor da compra.");\n  }\n  const financedBaseAmountCents = specialFirst == null ? input.baseAmountCents : input.baseAmountCents - specialFirst;\n  const interestAmountCents = Math.round((financedBaseAmountCents * input.interestBps) / 10_000);\n  const totalAmountCents = input.baseAmountCents + interestAmountCents;\n  if (!Number.isSafeInteger(totalAmountCents) || totalAmountCents > MAX_SAFE_MONEY_CENTS) {\n    throw new Error("Valor total fora do limite permitido.");\n  }\n\n  const amounts = specialFirst == null\n    ? splitInstallmentAmounts(totalAmountCents, input.installmentCount)\n    : [specialFirst, ...splitInstallmentAmounts(totalAmountCents - specialFirst, input.installmentCount - 1)];''', 'shared calculation')
t = once(t, '    interestAmountCents,\n    totalAmountCents,', '    interestAmountCents,\n    financedBaseAmountCents,\n    firstInstallmentAmountCents: specialFirst,\n    totalAmountCents,', 'shared return')
p.write_text(t, encoding='utf-8')

p = Path('server/routers/vipInstallments.ts')
t = p.read_text(encoding='utf-8')
t = once(t, '  defaultInterestBps: "vip_installments_interest_bps",\n  allowDaily:', '  defaultInterestBps: "vip_installments_interest_bps",\n  entryMode: "vip_installments_entry_mode",\n  entryFixedCents: "vip_installments_entry_fixed_cents",\n  entryPercentBps: "vip_installments_entry_percent_bps",\n  allowDaily:', 'setting keys')
t = once(t, '  defaultInterestBps: number;\n  allowDaily:', '  defaultInterestBps: number;\n  entryMode: "none" | "fixed" | "percent";\n  entryFixedCents: number;\n  entryPercentBps: number;\n  allowDaily:', 'config type')
t = once(t, '  const [enabled, minCount, maxCount, interestBps, allowDaily, allowWeekly, allowMonthly, dailyMode] = await Promise.all([', '  const [enabled, minCount, maxCount, interestBps, entryMode, entryFixedCents, entryPercentBps, allowDaily, allowWeekly, allowMonthly, dailyMode] = await Promise.all([', 'config vars')
t = once(t, '    getSetting(SETTING_KEYS.defaultInterestBps),\n    getSetting(SETTING_KEYS.allowDaily),', '    getSetting(SETTING_KEYS.defaultInterestBps),\n    getSetting(SETTING_KEYS.entryMode),\n    getSetting(SETTING_KEYS.entryFixedCents),\n    getSetting(SETTING_KEYS.entryPercentBps),\n    getSetting(SETTING_KEYS.allowDaily),', 'config settings')
t = once(t, '    defaultInterestBps: intSetting(interestBps, 0, 0, 100_000),\n    allowDaily:', '    defaultInterestBps: intSetting(interestBps, 0, 0, 100_000),\n    entryMode: entryMode === "fixed" || entryMode === "percent" ? entryMode : "none",\n    entryFixedCents: intSetting(entryFixedCents, 0, 0, MAX_FINANCIAL_SALE_CENTS),\n    entryPercentBps: intSetting(entryPercentBps, 0, 0, 9_999),\n    allowDaily:', 'config return')
t = once(t, '  const interestBps = eligibility.permission.interestBps ?? productRule.interestBps ?? eligibility.config.defaultInterestBps;\n  let quote;', '''  const interestBps = eligibility.permission.interestBps ?? productRule.interestBps ?? eligibility.config.defaultInterestBps;\n  let firstInstallmentAmountCents: number | null = null;\n  if (eligibility.config.entryMode === "fixed") firstInstallmentAmountCents = eligibility.config.entryFixedCents;\n  if (eligibility.config.entryMode === "percent") firstInstallmentAmountCents = Math.round((pricing.totalCents * eligibility.config.entryPercentBps) / 10_000);\n  if (firstInstallmentAmountCents != null) {\n    if (!Number.isSafeInteger(firstInstallmentAmountCents) || firstInstallmentAmountCents <= 0) throw new TRPCError({ code: "BAD_REQUEST", message: "Configure uma entrada válida no Parcelamento VIP." });\n    if (firstInstallmentAmountCents >= pricing.totalCents) throw new TRPCError({ code: "BAD_REQUEST", message: "A entrada deve ser menor que o valor da compra." });\n    if (pricing.totalCents - firstInstallmentAmountCents < input.installmentCount - 1) throw new TRPCError({ code: "BAD_REQUEST", message: "A entrada deixa saldo insuficiente para a quantidade de parcelas escolhida." });\n  }\n  let quote;''', 'entry resolve')
t = once(t, '      interestBps,\n      firstDueDate:', '      interestBps,\n      firstInstallmentAmountCents,\n      firstDueDate:', 'quote entry')
t = once(t, '      defaultInterestBps: z.number().int().min(0).max(100_000),\n      allowDaily:', '      defaultInterestBps: z.number().int().min(0).max(100_000),\n      entryMode: z.enum(["none", "fixed", "percent"]),\n      entryFixedCents: z.number().int().min(0).max(2_000_000_000),\n      entryPercentBps: z.number().int().min(0).max(9_999),\n      allowDaily:', 'admin schema')
t = once(t, '        upsertSetting(SETTING_KEYS.defaultInterestBps, String(input.defaultInterestBps)),\n        upsertSetting(SETTING_KEYS.allowDaily,', '        upsertSetting(SETTING_KEYS.defaultInterestBps, String(input.defaultInterestBps)),\n        upsertSetting(SETTING_KEYS.entryMode, input.entryMode),\n        upsertSetting(SETTING_KEYS.entryFixedCents, String(input.entryFixedCents)),\n        upsertSetting(SETTING_KEYS.entryPercentBps, String(input.entryPercentBps)),\n        upsertSetting(SETTING_KEYS.allowDaily,', 'admin save')
p.write_text(t, encoding='utf-8')

p = Path('client/src/components/AdminVipInstallmentsPanel.tsx')
t = p.read_text(encoding='utf-8')
t = once(t, '    defaultInterestPercent: "0",\n    allowDaily:', '    defaultInterestPercent: "0",\n    entryMode: "none" as "none" | "fixed" | "percent",\n    entryValue: "",\n    allowDaily:', 'admin state')
t = once(t, '      defaultInterestPercent: (data.defaultInterestBps / 100).toString().replace(".", ","),\n      allowDaily:', '      defaultInterestPercent: (data.defaultInterestBps / 100).toString().replace(".", ","),\n      entryMode: data.entryMode,\n      entryValue: data.entryMode === "fixed" ? centsToMoney(data.entryFixedCents) : data.entryMode === "percent" ? (data.entryPercentBps / 100).toString().replace(".", ",") : "",\n      allowDaily:', 'admin hydrate')
t = once(t, '    if (config.maxInstallments < config.minInstallments) {', '    const entryNumeric = config.entryMode === "none" ? 0 : Number(config.entryValue.replace(",", "."));\n    if (config.entryMode !== "none" && (!Number.isFinite(entryNumeric) || entryNumeric <= 0)) { toast.error("Informe uma entrada válida."); return; }\n    if (config.entryMode === "percent" && entryNumeric >= 100) { toast.error("A entrada percentual deve ser menor que 100%."); return; }\n    if (config.maxInstallments < config.minInstallments) {', 'admin validation')
t = once(t, '      defaultInterestBps: Math.round(interest * 100),\n      allowDaily:', '      defaultInterestBps: Math.round(interest * 100),\n      entryMode: config.entryMode,\n      entryFixedCents: config.entryMode === "fixed" ? Math.round(entryNumeric * 100) : 0,\n      entryPercentBps: config.entryMode === "percent" ? Math.round(entryNumeric * 100) : 0,\n      allowDaily:', 'admin payload')
t = once(t, '          <label className="text-[11px] font-black uppercase text-slate-300">Juros padrão (%)<input inputMode="decimal" value={config.defaultInterestPercent} onChange={(event) => setConfig((value) => ({ ...value, defaultInterestPercent: event.target.value }))} className={inputClass} /></label>\n          <label className="text-[11px] font-black uppercase text-slate-300">Regra diária', '          <label className="text-[11px] font-black uppercase text-slate-300">Juros padrão (%)<input inputMode="decimal" value={config.defaultInterestPercent} onChange={(event) => setConfig((value) => ({ ...value, defaultInterestPercent: event.target.value }))} className={inputClass} /></label>\n          <label className="text-[11px] font-black uppercase text-slate-300">Entrada / primeira parcela<select value={config.entryMode} onChange={(event) => setConfig((value) => ({ ...value, entryMode: event.target.value as "none" | "fixed" | "percent", entryValue: "" }))} className={inputClass}><option value="none">Sem entrada especial</option><option value="fixed">Valor fixo (R$)</option><option value="percent">Percentual (%)</option></select></label>\n          {config.entryMode !== "none" && <label className="text-[11px] font-black uppercase text-slate-300">{config.entryMode === "fixed" ? "Valor da entrada (R$)" : "Entrada (%)"}<input inputMode="decimal" value={config.entryValue} onChange={(event) => setConfig((value) => ({ ...value, entryValue: event.target.value }))} placeholder={config.entryMode === "fixed" ? "Ex.: 150,00" : "Ex.: 30"} className={inputClass} /><span className="mt-1 block normal-case font-medium text-slate-500">A entrada é a parcela 1. Os juros são aplicados somente no saldo restante.</span></label>}\n          <label className="text-[11px] font-black uppercase text-slate-300">Regra diária', 'admin fields')
p.write_text(t, encoding='utf-8')

p = Path('client/src/components/VipInstallmentCheckoutBox.tsx')
t = p.read_text(encoding='utf-8')
t = once(t, '<div className="mt-3 rounded-lg bg-violet-500/10 p-3 text-center"><p className="text-[10px] font-black uppercase text-violet-300">Primeira parcela agora</p><p className="mt-1 text-xl font-black text-white">{money(quote.data.quote.installments?.[0]?.amountCents)}</p><p className="mt-1 text-[11px] text-slate-400">Parcela 1 de {quote.data.quote.installmentCount}</p></div>', '<div className="mt-3 rounded-lg bg-violet-500/10 p-3 text-center"><p className="text-[10px] font-black uppercase text-violet-300">{quote.data.quote.firstInstallmentAmountCents != null ? "Entrada agora" : "Primeira parcela agora"}</p><p className="mt-1 text-xl font-black text-white">{money(quote.data.quote.installments?.[0]?.amountCents)}</p><p className="mt-1 text-[11px] text-slate-400">Parcela 1 de {quote.data.quote.installmentCount}{quote.data.quote.firstInstallmentAmountCents != null ? ` • Juros sobre ${money(quote.data.quote.financedBaseAmountCents)}` : ""}</p></div>', 'checkout label')
p.write_text(t, encoding='utf-8')

p = Path('shared/vipInstallments.test.ts')
t = p.read_text(encoding='utf-8')
t += '''\n\nit("uses a configured entry as installment 1 and charges interest only on remaining balance", () => {\n  const quote = calculateVipInstallmentQuote({\n    baseAmountCents: 45000,\n    installmentCount: 5,\n    interestBps: 1500,\n    firstInstallmentAmountCents: 15000,\n    firstDueDate: "2026-09-12",\n    frequency: "daily",\n    dailyMode: "all_days",\n  });\n  expect(quote.financedBaseAmountCents).toBe(30000);\n  expect(quote.interestAmountCents).toBe(4500);\n  expect(quote.totalAmountCents).toBe(49500);\n  expect(quote.installments.map((item) => item.amountCents)).toEqual([15000, 8625, 8625, 8625, 8625]);\n});\n'''
p.write_text(t, encoding='utf-8')
