import { ExternalLink, FileDown, MessageCircle, ReceiptText } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";

function money(value: unknown) { return Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function receiptLink(token: string) { return `${window.location.origin}/recibo/${token}`; }
function waLink(message: string) { return `https://wa.me/?text=${encodeURIComponent(message)}`; }

export function ReceiptsPanel({ token }: { token: string }) {
  const receiptsQuery = trpc.privateTransport.receipts.list.useQuery({ token }, { enabled: !!token });
  const receipts = receiptsQuery.data || [];
  return <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-slate-950/70 p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-cyan-300">H2 Particular • Recibos</p><h3 className="mt-1 text-xl font-black text-white">Recibos emitidos</h3><p className="mt-1 text-sm text-slate-400">Cada pagamento confirmado gera um recibo com link público seguro e PDF quando o armazenamento está disponível.</p></div>{receiptsQuery.isLoading ? <div className="h-48 animate-pulse rounded-2xl border border-white/5 bg-slate-900/60" /> : receipts.length === 0 ? <div className="rounded-2xl border border-dashed border-white/15 bg-slate-950/50 px-5 py-12 text-center"><ReceiptText className="mx-auto h-10 w-10 text-cyan-300/70" /><h4 className="mt-3 text-lg font-black text-white">Nenhum recibo emitido</h4><p className="mt-2 text-sm text-slate-400">Os recibos são gerados automaticamente após o registro de um pagamento.</p></div> : <div className="space-y-3">{receipts.map((receipt: any) => <div key={receipt.id} className="rounded-2xl border border-white/10 bg-slate-950/75 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h4 className="font-black text-white">{receipt.receiptCode}</h4><span className="rounded-full border border-emerald-400/25 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-black uppercase text-emerald-200">Emitido</span></div><p className="mt-2 text-sm text-slate-300">Pagamento em {new Date(receipt.paidAt).toLocaleString("pt-BR")}</p><p className="mt-1 text-lg font-black text-emerald-200">{money(receipt.amount)}</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => window.open(receiptLink(receipt.publicToken), "_blank", "noopener,noreferrer")} variant="outline" className="h-9 border-white/15 bg-white/5 text-xs font-bold text-white hover:bg-white/10"><ExternalLink className="mr-1.5 h-3.5 w-3.5" />Abrir</Button>{receipt.pdfUrl && <Button onClick={() => window.open(receipt.pdfUrl, "_blank", "noopener,noreferrer")} variant="outline" className="h-9 border-cyan-400/20 bg-cyan-500/10 text-xs font-bold text-cyan-100 hover:bg-cyan-500/20"><FileDown className="mr-1.5 h-3.5 w-3.5" />PDF</Button>}<Button onClick={() => { const link = receiptLink(receipt.publicToken); navigator.clipboard.writeText(link); window.open(waLink(`Seu recibo ${receipt.receiptCode} está disponível em: ${link}`), "_blank", "noopener,noreferrer"); toast.success("Link do recibo copiado."); }} variant="outline" className="h-9 border-emerald-400/20 bg-emerald-500/10 text-xs font-bold text-emerald-200 hover:bg-emerald-500/20"><MessageCircle className="mr-1.5 h-3.5 w-3.5" />Compartilhar</Button></div></div></div>)}</div>}</div>;
}
